version: '3.8'

services:
  test-db:
    image: postgres:15-alpine
    environment:
      - POSTGRES_DB=neoncasino_test
      - POSTGRES_USER=neoncasino
      - POSTGRES_PASSWORD=neoncasino_test
    ports:
      - "5433:5432"
    volumes:
      - test_postgres_data:/var/lib/postgresql/data

  test-redis:
    image: redis:7-alpine
    ports:
      - "6380:6379"
    volumes:
      - test_redis_data:/data

  test-minio:
    image: minio/minio:latest
    ports:
      - "9002:9000"
      - "9003:9001"
    environment:
      - MINIO_ROOT_USER=minioadmin
      - MINIO_ROOT_PASSWORD=minioadmin_test
    volumes:
      - test_minio_data:/data
    command: server /data --console-address ":9001"

  test-backend:
    build:
      context: ./backend
      target: development
    volumes:
      - ./backend:/app
    environment:
      - DEBUG=0
      - DJANGO_SETTINGS_MODULE=neoncasino.test_settings
      - DATABASE_URL=postgres://neoncasino:neoncasino_test@test-db:5432/neoncasino_test
      - REDIS_URL=redis://test-redis:6379/1
      - MINIO_ENDPOINT=test-minio:9000
      - MINIO_ACCESS_KEY=minioadmin
      - MINIO_SECRET_KEY=minioadmin_test
    depends_on:
      - test-db
      - test-redis
      - test-minio
    command: pytest --cov=. --cov-report=html --cov-report=term-missing

  test-frontend:
    build:
      context: ./frontend
      target: development
    volumes:
      - ./frontend:/app
      - /app/node_modules
      - /app/.next
    environment:
      - NODE_ENV=test
      - NEXT_TELEMETRY_DISABLED=1
    command: npm run test

volumes:
  test_postgres_data:
  test_redis_data:
  test_minio_data:



















