# Generated by Django 5.0.2 on 2025-08-19 10:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('promo', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PromoRule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rule_type', models.CharField(choices=[('MIN_AMOUNT', 'Minimum Amount'), ('MAX_AMOUNT', 'Maximum Amount'), ('USER_LIMIT', 'User Limit'), ('TIME_LIMIT', 'Time Limit'), ('GAME_RESTRICTION', 'Game Restriction'), ('PAYMENT_METHOD', 'Payment Method Restriction')], max_length=30)),
                ('rule_value', models.JSONField(help_text='Rule-specific value (e.g., amount, game list, etc.)')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('promo_code', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rules', to='promo.promocode')),
            ],
            options={
                'verbose_name': 'Promo Rule',
                'verbose_name_plural': 'Promo Rules',
                'ordering': ['rule_type'],
            },
        ),
    ]
