# Generated by Django 5.0.2 on 2025-08-19 10:49

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='gameachievement',
            name='badge_icon',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='gameachievement',
            name='metadata',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='gameachievement',
            name='rarity',
            field=models.CharField(choices=[('COMMON', 'Common'), ('RARE', 'Rare'), ('EPIC', 'Epic'), ('LEGENDARY', 'Legendary')], default='COMMON', max_length=20),
        ),
        migrations.AlterField(
            model_name='gameachievement',
            name='achievement_type',
            field=models.CharField(choices=[('FIRST_WIN', 'First Win'), ('BIG_WIN', 'Big Win'), ('WIN_STREAK', 'Win Streak'), ('HIGH_ROLLER', 'High Roller'), ('LUCKY_ONE', 'Lucky One'), ('MASTER_PLAYER', 'Master Player')], max_length=50),
        ),
        migrations.AlterUniqueTogether(
            name='gameachievement',
            unique_together={('user', 'game', 'achievement_type')},
        ),
        migrations.CreateModel(
            name='GameLeaderboard',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('period', models.CharField(choices=[('DAILY', 'Daily'), ('WEEKLY', 'Weekly'), ('MONTHLY', 'Monthly'), ('ALL_TIME', 'All Time')], max_length=20)),
                ('period_start', models.DateTimeField()),
                ('period_end', models.DateTimeField()),
                ('rankings', models.JSONField(default=list, help_text='List of user rankings')),
                ('total_players', models.PositiveIntegerField(default=0)),
                ('total_volume', models.DecimalField(decimal_places=2, default=0.0, max_digits=15)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('game', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='leaderboards', to='games.game')),
            ],
            options={
                'db_table': 'game_leaderboards',
                'ordering': ['-period_start'],
                'unique_together': {('game', 'period', 'period_start')},
            },
        ),
    ]
