# Generated by Django 5.0.2 on 2025-08-19 10:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kyc', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='KYCDocumentTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('document_type', models.CharField(choices=[('PASSPORT', 'Passport'), ('ID_CARD', 'National ID Card'), ('DRIVERS_LICENSE', "Driver's License"), ('UTILITY_BILL', 'Utility Bill'), ('BANK_STATEMENT', 'Bank Statement'), ('OTHER', 'Other')], max_length=20)),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('is_required', models.BooleanField(default=False)),
                ('max_file_size', models.PositiveIntegerField(default=5242880)),
                ('allowed_extensions', models.JSONField(default=list)),
                ('example_image', models.ImageField(blank=True, null=True, upload_to='kyc/templates/')),
                ('validation_rules', models.JSONField(default=dict)),
                ('instructions', models.TextField(blank=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'KYC Document Template',
                'verbose_name_plural': 'KYC Document Templates',
                'ordering': ['document_type', 'name'],
            },
        ),
        migrations.CreateModel(
            name='KYCRequirements',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('country', models.CharField(max_length=3, unique=True)),
                ('requires_kyc', models.BooleanField(default=True)),
                ('minimum_age', models.PositiveIntegerField(default=18)),
                ('verification_threshold', models.DecimalField(decimal_places=2, default=0.0, max_digits=15)),
                ('required_documents', models.JSONField(default=list)),
                ('optional_documents', models.JSONField(default=list)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'KYC Requirements',
                'verbose_name_plural': 'KYC Requirements',
                'ordering': ['country'],
            },
        ),
    ]
