# Generated by Django 5.0.2 on 2025-08-19 08:13

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DashboardWidget',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('widget_type', models.CharField(choices=[('CHART', 'Chart Widget'), ('TABLE', 'Table Widget'), ('METRIC', 'Metric Widget'), ('LIST', 'List Widget'), ('FORM', 'Form Widget'), ('CUSTOM', 'Custom Widget')], max_length=20)),
                ('data_source', models.CharField(choices=[('USERS', 'Users Data'), ('GAMES', 'Games Data'), ('TRANSACTIONS', 'Transactions Data'), ('PROMO', 'Promo Codes Data'), ('KYC', 'KYC Data'), ('CUSTOM', 'Custom Data Source')], max_length=20)),
                ('is_active', models.BooleanField(default=True)),
                ('data_config', models.JSONField(blank=True, default=dict)),
                ('refresh_interval', models.PositiveIntegerField(default=300, help_text='Refresh interval in seconds')),
                ('display_config', models.JSONField(blank=True, default=dict)),
                ('styling', models.JSONField(blank=True, default=dict)),
                ('position', models.JSONField(blank=True, default=dict)),
                ('last_refresh', models.DateTimeField(blank=True, null=True)),
                ('cache_duration', models.PositiveIntegerField(default=60, help_text='Cache duration in seconds')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Dashboard Widget',
                'verbose_name_plural': 'Dashboard Widgets',
                'db_table': 'dashboard_widgets',
                'ordering': ['widget_type', 'name'],
            },
        ),
        migrations.CreateModel(
            name='AdminDashboard',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('dashboard_type', models.CharField(choices=[('MAIN', 'Main Dashboard'), ('FINANCIAL', 'Financial Dashboard'), ('USER_MANAGEMENT', 'User Management Dashboard'), ('GAME_ANALYTICS', 'Game Analytics Dashboard'), ('SECURITY', 'Security Dashboard'), ('CUSTOM', 'Custom Dashboard')], default='MAIN', max_length=20)),
                ('is_active', models.BooleanField(default=True)),
                ('is_public', models.BooleanField(default=False)),
                ('layout_config', models.JSONField(blank=True, default=dict)),
                ('widget_config', models.JSONField(blank=True, default=dict)),
                ('permissions', models.JSONField(blank=True, default=dict)),
                ('last_accessed', models.DateTimeField(blank=True, null=True)),
                ('access_count', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='created_dashboards', to=settings.AUTH_USER_MODEL)),
                ('shared_with', models.ManyToManyField(blank=True, related_name='shared_dashboards', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Admin Dashboard',
                'verbose_name_plural': 'Admin Dashboards',
                'db_table': 'admin_dashboards',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='AdminNotification',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=255)),
                ('message', models.TextField()),
                ('notification_type', models.CharField(choices=[('INFO', 'Information'), ('WARNING', 'Warning'), ('ERROR', 'Error'), ('SUCCESS', 'Success'), ('ALERT', 'Alert')], default='INFO', max_length=20)),
                ('priority', models.CharField(choices=[('LOW', 'Low'), ('MEDIUM', 'Medium'), ('HIGH', 'High'), ('CRITICAL', 'Critical')], default='MEDIUM', max_length=20)),
                ('is_broadcast', models.BooleanField(default=False, help_text='Send to all admin users')),
                ('is_read', models.BooleanField(default=False)),
                ('expires_at', models.DateTimeField(blank=True, null=True)),
                ('source_app', models.CharField(blank=True, max_length=50)),
                ('source_action', models.CharField(blank=True, max_length=100)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('read_by', models.ManyToManyField(blank=True, related_name='read_notifications', to=settings.AUTH_USER_MODEL)),
                ('target_users', models.ManyToManyField(blank=True, related_name='admin_notifications', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Admin Notification',
                'verbose_name_plural': 'Admin Notifications',
                'db_table': 'admin_notifications',
                'ordering': ['-priority', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='DashboardLayout',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('layout_type', models.CharField(choices=[('GRID', 'Grid Layout'), ('FLEXBOX', 'Flexbox Layout'), ('CSS_GRID', 'CSS Grid Layout'), ('RESPONSIVE', 'Responsive Layout'), ('CUSTOM', 'Custom Layout')], default='GRID', max_length=20)),
                ('is_default', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('grid_config', models.JSONField(blank=True, default=dict)),
                ('responsive_breakpoints', models.JSONField(blank=True, default=dict)),
                ('widget_positions', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('default_widgets', models.ManyToManyField(blank=True, to='admin_dashboard.dashboardwidget')),
            ],
            options={
                'verbose_name': 'Dashboard Layout',
                'verbose_name_plural': 'Dashboard Layouts',
                'db_table': 'dashboard_layouts',
                'ordering': ['-created_at'],
            },
        ),
    ]
