# Generated by Django 5.0.2 on 2025-08-27 08:42

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_dashboard', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AuditLog',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('action', models.CharField(choices=[('CREATE', 'Create'), ('UPDATE', 'Update'), ('DELETE', 'Delete'), ('VIEW', 'View'), ('APPROVE', 'Approve'), ('REJECT', 'Reject'), ('BAN', 'Ban'), ('UNBAN', 'Unban'), ('LOGIN', 'Login'), ('LOGOUT', 'Logout'), ('EXPORT', 'Export'), ('IMPORT', 'Import'), ('BULK_ACTION', 'Bulk Action')], max_length=20)),
                ('resource_type', models.CharField(choices=[('USER', 'User'), ('GAME', 'Game'), ('TRANSACTION', 'Transaction'), ('KYC', 'KYC Document'), ('PROMO', 'Promo Code'), ('PAYMENT', 'Payment'), ('SETTING', 'System Setting'), ('AUDIT_LOG', 'Audit Log')], max_length=20)),
                ('resource_id', models.CharField(blank=True, max_length=100)),
                ('details', models.JSONField(blank=True, default=dict)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('user_agent', models.TextField(blank=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('performed_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='audit_actions', to=settings.AUTH_USER_MODEL)),
                ('target_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='audit_targets', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'admin_dashboard_auditlog',
                'ordering': ['-timestamp'],
                'indexes': [models.Index(fields=['action', 'timestamp'], name='admin_dashb_action_ed536c_idx'), models.Index(fields=['resource_type', 'resource_id'], name='admin_dashb_resourc_a354e7_idx'), models.Index(fields=['performed_by', 'timestamp'], name='admin_dashb_perform_149f3f_idx'), models.Index(fields=['target_user', 'timestamp'], name='admin_dashb_target__14d332_idx')],
            },
        ),
    ]
