# Generated by Django 5.0.2 on 2025-08-20 17:05

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BotNotification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('notification_type', models.CharField(choices=[('user_registration', 'User Registration'), ('payment_created', 'Payment Created'), ('payment_status_changed', 'Payment Status Changed'), ('kyc_submitted', 'KYC Submitted'), ('kyc_approved', 'KYC Approved'), ('kyc_rejected', 'KYC Rejected'), ('admin_alert', 'Admin Alert'), ('system_alert', 'System Alert')], max_length=50)),
                ('message', models.TextField()),
                ('sent_to', models.CharField(max_length=100)),
                ('sent_at', models.DateTimeField(auto_now_add=True)),
                ('is_sent', models.BooleanField(default=False)),
                ('error_message', models.TextField(blank=True)),
            ],
            options={
                'verbose_name': 'Bot Notification',
                'verbose_name_plural': 'Bot Notifications',
                'ordering': ['-sent_at'],
            },
        ),
        migrations.CreateModel(
            name='BotSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bot_token', models.CharField(max_length=100, unique=True)),
                ('admin_chat_id', models.CharField(default='-1002802840685', max_length=100)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Bot Settings',
                'verbose_name_plural': 'Bot Settings',
            },
        ),
        migrations.CreateModel(
            name='AdminCommand',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('command_type', models.CharField(choices=[('approve_payment', 'Approve Payment'), ('reject_payment', 'Reject Payment'), ('approve_kyc', 'Approve KYC'), ('reject_kyc', 'Reject KYC'), ('ban_user', 'Ban User'), ('unban_user', 'Unban User'), ('system_status', 'System Status')], max_length=50)),
                ('target_id', models.CharField(max_length=100)),
                ('executed_at', models.DateTimeField(auto_now_add=True)),
                ('is_executed', models.BooleanField(default=False)),
                ('result_message', models.TextField(blank=True)),
                ('admin_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Admin Command',
                'verbose_name_plural': 'Admin Commands',
                'ordering': ['-executed_at'],
            },
        ),
    ]
