# Generated by Django 5.0.2 on 2025-08-21 11:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('telegram_bot_new', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='botsettings',
            name='managers_chat_id',
            field=models.CharField(blank=True, help_text='Chat ID for managers notifications', max_length=100, null=True),
        ),
    ]
