# Generated by Django 5.0.2 on 2025-08-21 11:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('telegram_bot_new', '0002_botsettings_managers_chat_id'),
    ]

    operations = [
    ]
