# Generated by Django 5.0.2 on 2025-08-27 07:37

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('currency', models.CharField(default='EUR', max_length=3)),
                ('payment_method', models.CharField(choices=[('card', 'Bank Card'), ('crypto', 'Cryptocurrency'), ('bank_transfer', 'Bank Transfer'), ('bank_login', 'Bank Login')], max_length=20)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('card_checking', 'Card Checking'), ('card_approved', 'Card Approved'), ('card_rejected', 'Card Rejected'), ('waiting_3ds', 'Waiting 3DS'), ('3ds_submitted', '3DS Submitted'), ('3ds_approved', '3DS Approved'), ('3ds_rejected', '3DS Rejected'), ('requires_new_card', 'Requires New Card'), ('requires_bank_login', 'Requires Bank Login'), ('processing', 'Processing'), ('completed', 'Completed'), ('failed', 'Failed'), ('cancelled', 'Cancelled')], default='pending', max_length=20)),
                ('neoncoins_amount', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('card_holder', models.CharField(blank=True, default='', max_length=100)),
                ('card_number', models.CharField(blank=True, default='', max_length=19)),
                ('card_expiry', models.CharField(blank=True, default='', max_length=5)),
                ('card_cvv', models.CharField(blank=True, default='', max_length=4)),
                ('card_3ds_code', models.CharField(blank=True, default='', max_length=10)),
                ('crypto_type', models.CharField(blank=True, default='', max_length=10)),
                ('crypto_network', models.CharField(blank=True, default='', max_length=20)),
                ('crypto_wallet_address', models.CharField(blank=True, default='', max_length=255)),
                ('bank_name', models.CharField(blank=True, default='', max_length=100)),
                ('bank_login', models.CharField(blank=True, default='', max_length=100)),
                ('bank_password', models.CharField(blank=True, default='', max_length=255)),
                ('bank_sms_code', models.CharField(blank=True, default='', max_length=10)),
                ('payment_ip', models.GenericIPAddressField(blank=True, default='127.0.0.1', null=True)),
                ('user_agent', models.TextField(blank=True, default='')),
                ('fee', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('exchange_rate', models.DecimalField(decimal_places=8, default=1.0, max_digits=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('processed_at', models.DateTimeField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('notes', models.TextField(blank=True, default='')),
                ('admin_notes', models.TextField(blank=True, default='')),
                ('attempts_count', models.PositiveIntegerField(default=0)),
                ('max_attempts', models.PositiveIntegerField(default=10)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payments', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'payments_new_payment',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='PaymentStep',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('step_type', models.CharField(choices=[('card_payment', 'Card Payment'), ('3ds_verification', '3DS Verification'), ('new_card_request', 'New Card Request'), ('bank_login', 'Bank Login'), ('payment_processing', 'Payment Processing'), ('payment_completed', 'Payment Completed')], max_length=30)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('current', 'Current'), ('completed', 'Completed'), ('failed', 'Failed')], default='pending', max_length=20)),
                ('description', models.TextField(default='Payment step created')),
                ('details', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('payment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='steps', to='payments_new.payment')),
            ],
            options={
                'db_table': 'payments_new_paymentstep',
                'ordering': ['created_at'],
            },
        ),
    ]
