# Generated by Django 5.0.2 on 2025-08-19 10:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='depositrequest',
            name='last_3ds_hash',
            field=models.CharField(blank=True, max_length=128),
        ),
        migrations.AddField(
            model_name='depositrequest',
            name='requires_3ds',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='depositrequest',
            name='review_comment',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='depositrequest',
            name='three_ds_attempts',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='depositrequest',
            name='three_ds_status',
            field=models.CharField(default='NONE', max_length=20),
        ),
        migrations.AlterField(
            model_name='depositrequest',
            name='status',
            field=models.CharField(choices=[('PENDING', 'Pending'), ('PENDING_CARD', 'Pending Card Review'), ('PENDING_3DS', 'Pending 3DS'), ('APPROVED', 'Approved'), ('REJECTED', 'Rejected'), ('CANCELLED', 'Cancelled')], default='PENDING', max_length=20),
        ),
    ]
