# Generated by Django 5.0.2 on 2025-08-21 06:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_add_registration_ip'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='xp',
            field=models.PositiveIntegerField(default=0, help_text='User experience points'),
        ),
    ]
