# Generated by Django 5.0.2 on 2025-08-21 07:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_user_xp'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='balance_neon',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=15),
        ),
    ]
